config/routes.rb
Kurs::Application.routes.draw do
  
  

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users

  resources :users do
    resources :carts
  end

  match 'cars/news' => 'cars#news'

  resources :makes
  resources :models
  resources :cars do
    resources :pictures
    resources :options
    resources :reviews
    resources :news
  end

  resources :line_items, :only => [:create, :destroy]
  
  match 'movies/latest' => 'movies#latest'
  match 'movies/top_rated' => 'movies#top_rated'
  match 'movies/coming' => 'movies#coming'
  match 'movies/top_commented' => 'movies#top_commented'
  match 'movies/votes' => 'movies#votes'
  match 'movies/comments' => 'movies#index'
  match 'movies/search' => "movies#search"

  resources :movies, :only => [:index, :show] do
    resources :comments
  end

  match 'auto' => 'auto/cars#index'
  match 'auto/news' => 'auto/cars#news'
  match 'new_cars' => 'cars#new_cars'
  match 'used_cars' => 'cars#used_cars'

  resources :news, :only => [:index, :show] do
    resources :comments
  end

  resources :categories, :only => [:index, :show] do
    resources :products, :only => [:index, :show]
  end

  resources :manufacturers, :only => [:show]

  resources :products, :only => [:index]
  

  root :to => 'pages#home'

  match 'our_news' => 'pages#news'
  match 'our_services' => 'pages#services'
  match 'our_products' => 'pages#products'
  match 'contacts' => 'pages#contacts'
  
end
#== Route Map
# Generated on 25 Sep 2011 20:32
#
#                 auto_makes GET        /auto/makes(.:format)                {:action=>"index", :controller=>"auto/makes"}
#                            POST       /auto/makes(.:format)                {:action=>"create", :controller=>"auto/makes"}
#              new_auto_make GET        /auto/makes/new(.:format)            {:action=>"new", :controller=>"auto/makes"}
#             edit_auto_make GET        /auto/makes/:id/edit(.:format)       {:action=>"edit", :controller=>"auto/makes"}
#                  auto_make GET        /auto/makes/:id(.:format)            {:action=>"show", :controller=>"auto/makes"}
#                            PUT        /auto/makes/:id(.:format)            {:action=>"update", :controller=>"auto/makes"}
#                            DELETE     /auto/makes/:id(.:format)            {:action=>"destroy", :controller=>"auto/makes"}
#                auto_models GET        /auto/models(.:format)               {:action=>"index", :controller=>"auto/models"}
#                            POST       /auto/models(.:format)               {:action=>"create", :controller=>"auto/models"}
#             new_auto_model GET        /auto/models/new(.:format)           {:action=>"new", :controller=>"auto/models"}
#            edit_auto_model GET        /auto/models/:id/edit(.:format)      {:action=>"edit", :controller=>"auto/models"}
#                 auto_model GET        /auto/models/:id(.:format)           {:action=>"show", :controller=>"auto/models"}
#                            PUT        /auto/models/:id(.:format)           {:action=>"update", :controller=>"auto/models"}
#                            DELETE     /auto/models/:id(.:format)           {:action=>"destroy", :controller=>"auto/models"}
#                  auto_cars GET        /auto/cars(.:format)                 {:action=>"index", :controller=>"auto/cars"}
#                            POST       /auto/cars(.:format)                 {:action=>"create", :controller=>"auto/cars"}
#               new_auto_car GET        /auto/cars/new(.:format)             {:action=>"new", :controller=>"auto/cars"}
#              edit_auto_car GET        /auto/cars/:id/edit(.:format)        {:action=>"edit", :controller=>"auto/cars"}
#                   auto_car GET        /auto/cars/:id(.:format)             {:action=>"show", :controller=>"auto/cars"}
#                            PUT        /auto/cars/:id(.:format)             {:action=>"update", :controller=>"auto/cars"}
#                            DELETE     /auto/cars/:id(.:format)             {:action=>"destroy", :controller=>"auto/cars"}
#               auto_options GET        /auto/options(.:format)              {:action=>"index", :controller=>"auto/options"}
#                            POST       /auto/options(.:format)              {:action=>"create", :controller=>"auto/options"}
#            new_auto_option GET        /auto/options/new(.:format)          {:action=>"new", :controller=>"auto/options"}
#           edit_auto_option GET        /auto/options/:id/edit(.:format)     {:action=>"edit", :controller=>"auto/options"}
#                auto_option GET        /auto/options/:id(.:format)          {:action=>"show", :controller=>"auto/options"}
#                            PUT        /auto/options/:id(.:format)          {:action=>"update", :controller=>"auto/options"}
#                            DELETE     /auto/options/:id(.:format)          {:action=>"destroy", :controller=>"auto/options"}
#            auto_categories GET        /auto/categories(.:format)           {:action=>"index", :controller=>"auto/categories"}
#                            POST       /auto/categories(.:format)           {:action=>"create", :controller=>"auto/categories"}
#          new_auto_category GET        /auto/categories/new(.:format)       {:action=>"new", :controller=>"auto/categories"}
#         edit_auto_category GET        /auto/categories/:id/edit(.:format)  {:action=>"edit", :controller=>"auto/categories"}
#              auto_category GET        /auto/categories/:id(.:format)       {:action=>"show", :controller=>"auto/categories"}
#                            PUT        /auto/categories/:id(.:format)       {:action=>"update", :controller=>"auto/categories"}
#                            DELETE     /auto/categories/:id(.:format)       {:action=>"destroy", :controller=>"auto/categories"}
#                       auto            /auto(.:format)                      {:action=>"auto", :controller=>"pages"}
#             auto_cars_news            /auto/cars/news(.:format)            {:controller=>"auto/cars", :action=>"news"}
#            admin_dashboard            /admin(.:format)                     {:action=>"index", :controller=>"admin/dashboard"}
#             admin_comments GET        /admin/comments(.:format)            {:action=>"index", :controller=>"admin/comments"}
#                            POST       /admin/comments(.:format)            {:action=>"create", :controller=>"admin/comments"}
#          new_admin_comment GET        /admin/comments/new(.:format)        {:action=>"new", :controller=>"admin/comments"}
#         edit_admin_comment GET        /admin/comments/:id/edit(.:format)   {:action=>"edit", :controller=>"admin/comments"}
#              admin_comment GET        /admin/comments/:id(.:format)        {:action=>"show", :controller=>"admin/comments"}
#                            PUT        /admin/comments/:id(.:format)        {:action=>"update", :controller=>"admin/comments"}
#                            DELETE     /admin/comments/:id(.:format)        {:action=>"destroy", :controller=>"admin/comments"}
#             admin_products GET        /admin/products(.:format)            {:action=>"index", :controller=>"admin/products"}
#                            POST       /admin/products(.:format)            {:action=>"create", :controller=>"admin/products"}
#          new_admin_product GET        /admin/products/new(.:format)        {:action=>"new", :controller=>"admin/products"}
#         edit_admin_product GET        /admin/products/:id/edit(.:format)   {:action=>"edit", :controller=>"admin/products"}
#              admin_product GET        /admin/products/:id(.:format)        {:action=>"show", :controller=>"admin/products"}
#                            PUT        /admin/products/:id(.:format)        {:action=>"update", :controller=>"admin/products"}
#                            DELETE     /admin/products/:id(.:format)        {:action=>"destroy", :controller=>"admin/products"}
#           admin_categories GET        /admin/categories(.:format)          {:action=>"index", :controller=>"admin/categories"}
#                            POST       /admin/categories(.:format)          {:action=>"create", :controller=>"admin/categories"}
#         new_admin_category GET        /admin/categories/new(.:format)      {:action=>"new", :controller=>"admin/categories"}
#        edit_admin_category GET        /admin/categories/:id/edit(.:format) {:action=>"edit", :controller=>"admin/categories"}
#             admin_category GET        /admin/categories/:id(.:format)      {:action=>"show", :controller=>"admin/categories"}
#                            PUT        /admin/categories/:id(.:format)      {:action=>"update", :controller=>"admin/categories"}
#                            DELETE     /admin/categories/:id(.:format)      {:action=>"destroy", :controller=>"admin/categories"}
#           admin_news_index GET        /admin/news(.:format)                {:action=>"index", :controller=>"admin/news"}
#                            POST       /admin/news(.:format)                {:action=>"create", :controller=>"admin/news"}
#             new_admin_news GET        /admin/news/new(.:format)            {:action=>"new", :controller=>"admin/news"}
#            edit_admin_news GET        /admin/news/:id/edit(.:format)       {:action=>"edit", :controller=>"admin/news"}
#                 admin_news GET        /admin/news/:id(.:format)            {:action=>"show", :controller=>"admin/news"}
#                            PUT        /admin/news/:id(.:format)            {:action=>"update", :controller=>"admin/news"}
#                            DELETE     /admin/news/:id(.:format)            {:action=>"destroy", :controller=>"admin/news"}
#     new_admin_user_session GET        /admin/login(.:format)               {:action=>"new", :controller=>"active_admin/devise/sessions"}

app/controllers/movies_controller.rb
class MoviesController < InheritedResources::Base
	layout 'movies/movies'
	before_filter :load_search
	
	def index

		@movies = Movie.scoped
		@news = News.movies.limit(5)
	end

	def latest
		@movies = Movie.recent
		@type = I18n.t("latest")
		render "movies"
	end

	def coming
		@movies = Movie.coming
		@type = I18n.t("coming_soon")
		render "movies"
	end

	def top_rated
		@movies = Movie.top_rated
		@type = I18n.t("top_rated")
		render "movies"
	end

	def votes
		@movies = Movie.find(params[:id])
		@movies.liked_by current_user
		redirect_to :back, :notice => "Thanx"
	end

	def top_commented
		@movies = Movie.top_commented
		@type = I18n.t("most_commented")
		render "movies"
	end

	def search
		@search = Movie.search(params[:search])
		@movies = @search.all
	end

	private

		def load_search
			@search = Movie.search(params[:search])
		end
	
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_coming.html.erb
<%= content_for :coming do %>
	<div id="coming">
	  <div class="head">
	    <h3><%= I18n.t("coming_soon") %><strong>!</strong></h3>
	    <p class="text-right"><%= link_to I18n.t("see_all"), movies_coming_path %></p>
	  </div>
	  <% if @movies.coming.exists? %>
	  <% for movie in @movies.coming.limit(5) %>
	  <div class="content">
	    <h4><%= movie.name %></h4>
	    <p class="date"><%= time_ago_in_words(movie.release_date) %></p>
	    <%= link_to image_tag(movie.pictures.first.image.url), movie if movie.pictures.exists? %>
	    <%= movie.description %>
	  	<%= link_to I18n.t("read_more"), movie %>  
	  </div>
	  <div class="cl">&nbsp;</div>
	</div>
	<% end %>
	<% end %>
<% end %>

app/views/movies/_latest.html.erb
<div class="box">
  <div class="head">
    <h2><%= I18n.t("latest") %></h2>
    <p class="text-right"><%= link_to I18n.t("see_all"), movies_latest_path %></p>
  </div>
  <% if @movies.recent.exists? %>
  <% for movie in @movies.recent %>
  <div class="movie">
    <div class="movie-image"><span class="name"><%= movie.name %></span>
      <%= link_to image_tag(movie.pictures.first.image.url, :width => 152), movie if movie.pictures.exists? %>
    </div>
    <div class="rating">
      <p><%= I18n.t("rating") %></p>
      <div class="stars">
        <div class="stars-in"> </div>
      </div>
      <span class="comments">12</span>
    </div>
  </div>
  <% end %>
  <% end %>
  <div class="cl">&nbsp;</div>
</div>

app/views/movies/_most_commented.html.erb
<div class="box">
  <div class="head">
    <h2><%= I18n.t("most_commented") %></h2>
    <p class="text-right"><%= link_to I18n.t("see_all"), movies_top_commented_path %></p>
  </div>
  <% if @movies.top_commented.exists? %>
  <% for movie in @movies.top_commented.limit(12) %>
  <div class="movie">
    <div class="movie-image"><span class="name"><%= movie.name %></span>
      <%= link_to image_tag(movie.pictures.first.image.url, :width => 152), movie if movie.pictures.exists? %>
    </div>
    <div class="rating">
      <p><%= I18n.t("rating") %></p>
      <div class="stars">
        <div class="stars-in"> </div>
      </div>
      <span class="comments">12</span>
    </div>
  </div>
  <% end %>
  <% end %>
  <div class="cl">&nbsp;</div>
</div>

app/views/movies/_news.html.erb
<%= content_for :news do %>
  <div id="news">
    <div class="head">
      <h3><%= I18n.t("news") %></h3>
      <p class="text-right"><%= link_to I18n.t("see_all"), news_index_path+"?news_type=movies" %></p>
    </div>
    <% for news in @news %>
      <div class="content">
        <p class="date"><%= time_ago_in_words(news.created_at) %></p>
        <h4><%= news.name %></h4>
        <p><%= news.body %></p>
        <%= link_to I18n.t("read_more"), news %>
      </div>
    <% end %>
  </div>
<% end %> 

app/views/movies/_top_rated.html.erb
<div class="box">
  <div class="head">
    <h2><%= I18n.t("top_rated") %></h2>
    <p class="text-right"><%= link_to I18n.t("see_all"), movies_top_rated_path %></p>
  </div>
  <% if @movies.top_rated.exists? %>
  <% for movie in @movies.top_rated.limit(12) %>
  <div class="movie">
    <div class="movie-image"><span class="name"><%= movie.name %></span>
      <%= link_to image_tag(movie.pictures.first.image.url, :width => 152), movie if movie.pictures.exists? %>
    </div>
    <div class="rating">
      <p>RATING</p>
      <div class="stars">
        <div class="stars-in"> </div>
      </div>
      <span class="comments">12</span>
    </div>
  </div>
  <% end %>
  <% end %>
  <div class="cl">&nbsp;</div>
</div>

app/views/movies/index.html.erb
<div id="content">
    <%= render :partial => "latest" %>
    <%= render :partial => "top_rated" %>
    <%= render :partial => "most_commented" %>
</div>



<%= render :partial => "news" %>
<%= render :partial => "coming" %>

app/views/movies/movies.html.erb
<div class="box">
  <div class="head">
    <h2><%= @type %></h2>
    <p class="text-right"><%= @type %></p>
  </div>
  <% for movie in @movies %>
  <div class="movie">
    <div class="movie-image"><span class="name"><%= movie.name %></span>
      <%= link_to image_tag(movie.pictures.first.image.url, :width => 152), movie if movie.pictures.exists? %>
    </div>
    <div class="rating">
      <p><%= I18n.t("rating") %></p>
      <div class="stars">
        <div class="stars-in"> </div>
      </div>
      <span class="comments">12</span>
    </div>
  </div>
  <% end %>
  <div class="cl">&nbsp;</div>
</div>

app/views/movies/search.html.erb
<div class="box">
  <div class="head">
    <h2>SEARCH RESULT</h2>
    <p class="text-right">SEARCH RESULT</p>
  </div>
  <% for movie in @movies %>
  <div class="movie">
    <div class="movie-image"><span class="name"><%= movie.name %></span>
      <%= link_to image_tag(movie.pictures.first.image.url, :width => 152), movie %>
    </div>
    <div class="rating">
      <p>RATING</p>
      <div class="stars">
        <div class="stars-in"> </div>
      </div>
      <span class="comments">12</span>
    </div>
  </div>
  <% end %>
  <div class="cl">&nbsp;</div>
</div>

app/views/movies/show.html.erb
<div class="box">
  <div class="photo"><%= image_tag @movie.pictures.first.image.url, :width => 200 %></div>
  <div class="desc">
    <table>
      <tr>
        <td><h4>Name</h4></td>
        <td><%= @movie.name %></td>
      </tr>
      <tr>
        <td><h4>Genre</h4></td>
        <td><%= @movie.genre %></td>
      </tr>
      <tr>
        <td><h4>Year</h4></td>
        <td><%= @movie.year %></td>
      </tr>
      <tr>
        <td><h4>Time</h4></td>
        <td><%= @movie.time %></td>
      </tr>
      <tr>
        <td><h4>Distributors</h4></td>
        <td><%= @movie.distributors %></td>
      </tr>
      <tr>
        <td><h4>Rate</h4></td>
        <td><%= @movie.votes.size %></td>
      </tr>
      <tr>
        <td><h4>Release</h4></td>
        <td><%= time_ago_in_words @movie.release_date if !@movie.release_date.nil? %></td>
      </tr>
    </table>
  </div>
  <%= button_to "Like", :action => "votes", :id => @movie.id if user_signed_in? %>
  <div class="description"><%= @movie.description %></div>
  <p><%= link_to "Comments", movie_comments_path(@movie) %></p>
</div>