config/routes.rb
Kurs::Application.routes.draw do
  
  

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users

  resources :users do
    resources :carts
  end

  match 'cars/news' => 'cars#news'

  resources :makes
  resources :models
  resources :cars do
    resources :pictures
    resources :options
    resources :reviews
    resources :news
  end

  resources :line_items, :only => [:create, :destroy]
  
  match 'movies/latest' => 'movies#latest'
  match 'movies/top_rated' => 'movies#top_rated'
  match 'movies/coming' => 'movies#coming'
  match 'movies/top_commented' => 'movies#top_commented'
  match 'movies/votes' => 'movies#votes'
  match 'movies/comments' => 'movies#index'
  match 'movies/search' => "movies#search"

  resources :movies, :only => [:index, :show] do
    resources :comments
  end

  match 'auto' => 'auto/cars#index'
  match 'auto/news' => 'auto/cars#news'
  match 'new_cars' => 'cars#new_cars'
  match 'used_cars' => 'cars#used_cars'

  resources :news, :only => [:index, :show] do
    resources :comments
  end

  resources :categories, :only => [:index, :show] do
    resources :products, :only => [:index, :show]
  end

  resources :manufacturers, :only => [:show]

  resources :products, :only => [:index]
  

  root :to => 'pages#home'

  match 'our_news' => 'pages#news'
  match 'our_services' => 'pages#services'
  match 'our_products' => 'pages#products'
  match 'contacts' => 'pages#contacts'
  
end
#== Route Map
# Generated on 25 Sep 2011 20:32
#
#                 auto_makes GET        /auto/makes(.:format)                {:action=>"index", :controller=>"auto/makes"}
#                            POST       /auto/makes(.:format)                {:action=>"create", :controller=>"auto/makes"}
#              new_auto_make GET        /auto/makes/new(.:format)            {:action=>"new", :controller=>"auto/makes"}
#             edit_auto_make GET        /auto/makes/:id/edit(.:format)       {:action=>"edit", :controller=>"auto/makes"}
#                  auto_make GET        /auto/makes/:id(.:format)            {:action=>"show", :controller=>"auto/makes"}
#                            PUT        /auto/makes/:id(.:format)            {:action=>"update", :controller=>"auto/makes"}
#                            DELETE     /auto/makes/:id(.:format)            {:action=>"destroy", :controller=>"auto/makes"}
#                auto_models GET        /auto/models(.:format)               {:action=>"index", :controller=>"auto/models"}
#                            POST       /auto/models(.:format)               {:action=>"create", :controller=>"auto/models"}
#             new_auto_model GET        /auto/models/new(.:format)           {:action=>"new", :controller=>"auto/models"}
#            edit_auto_model GET        /auto/models/:id/edit(.:format)      {:action=>"edit", :controller=>"auto/models"}
#                 auto_model GET        /auto/models/:id(.:format)           {:action=>"show", :controller=>"auto/models"}
#                            PUT        /auto/models/:id(.:format)           {:action=>"update", :controller=>"auto/models"}
#                            DELETE     /auto/models/:id(.:format)           {:action=>"destroy", :controller=>"auto/models"}
#                  auto_cars GET        /auto/cars(.:format)                 {:action=>"index", :controller=>"auto/cars"}
#                            POST       /auto/cars(.:format)                 {:action=>"create", :controller=>"auto/cars"}
#               new_auto_car GET        /auto/cars/new(.:format)             {:action=>"new", :controller=>"auto/cars"}
#              edit_auto_car GET        /auto/cars/:id/edit(.:format)        {:action=>"edit", :controller=>"auto/cars"}
#                   auto_car GET        /auto/cars/:id(.:format)             {:action=>"show", :controller=>"auto/cars"}
#                            PUT        /auto/cars/:id(.:format)             {:action=>"update", :controller=>"auto/cars"}
#                            DELETE     /auto/cars/:id(.:format)             {:action=>"destroy", :controller=>"auto/cars"}
#               auto_options GET        /auto/options(.:format)              {:action=>"index", :controller=>"auto/options"}
#                            POST       /auto/options(.:format)              {:action=>"create", :controller=>"auto/options"}
#            new_auto_option GET        /auto/options/new(.:format)          {:action=>"new", :controller=>"auto/options"}
#           edit_auto_option GET        /auto/options/:id/edit(.:format)     {:action=>"edit", :controller=>"auto/options"}
#                auto_option GET        /auto/options/:id(.:format)          {:action=>"show", :controller=>"auto/options"}
#                            PUT        /auto/options/:id(.:format)          {:action=>"update", :controller=>"auto/options"}
#                            DELETE     /auto/options/:id(.:format)          {:action=>"destroy", :controller=>"auto/options"}
#            auto_categories GET        /auto/categories(.:format)           {:action=>"index", :controller=>"auto/categories"}
#                            POST       /auto/categories(.:format)           {:action=>"create", :controller=>"auto/categories"}
#          new_auto_category GET        /auto/categories/new(.:format)       {:action=>"new", :controller=>"auto/categories"}
#         edit_auto_category GET        /auto/categories/:id/edit(.:format)  {:action=>"edit", :controller=>"auto/categories"}
#              auto_category GET        /auto/categories/:id(.:format)       {:action=>"show", :controller=>"auto/categories"}
#                            PUT        /auto/categories/:id(.:format)       {:action=>"update", :controller=>"auto/categories"}
#                            DELETE     /auto/categories/:id(.:format)       {:action=>"destroy", :controller=>"auto/categories"}
#                       auto            /auto(.:format)                      {:action=>"auto", :controller=>"pages"}
#             auto_cars_news            /auto/cars/news(.:format)            {:controller=>"auto/cars", :action=>"news"}
#            admin_dashboard            /admin(.:format)                     {:action=>"index", :controller=>"admin/dashboard"}
#             admin_comments GET        /admin/comments(.:format)            {:action=>"index", :controller=>"admin/comments"}
#                            POST       /admin/comments(.:format)            {:action=>"create", :controller=>"admin/comments"}
#          new_admin_comment GET        /admin/comments/new(.:format)        {:action=>"new", :controller=>"admin/comments"}
#         edit_admin_comment GET        /admin/comments/:id/edit(.:format)   {:action=>"edit", :controller=>"admin/comments"}
#              admin_comment GET        /admin/comments/:id(.:format)        {:action=>"show", :controller=>"admin/comments"}
#                            PUT        /admin/comments/:id(.:format)        {:action=>"update", :controller=>"admin/comments"}
#                            DELETE     /admin/comments/:id(.:format)        {:action=>"destroy", :controller=>"admin/comments"}
#             admin_products GET        /admin/products(.:format)            {:action=>"index", :controller=>"admin/products"}
#                            POST       /admin/products(.:format)            {:action=>"create", :controller=>"admin/products"}
#          new_admin_product GET        /admin/products/new(.:format)        {:action=>"new", :controller=>"admin/products"}
#         edit_admin_product GET        /admin/products/:id/edit(.:format)   {:action=>"edit", :controller=>"admin/products"}
#              admin_product GET        /admin/products/:id(.:format)        {:action=>"show", :controller=>"admin/products"}
#                            PUT        /admin/products/:id(.:format)        {:action=>"update", :controller=>"admin/products"}
#                            DELETE     /admin/products/:id(.:format)        {:action=>"destroy", :controller=>"admin/products"}
#           admin_categories GET        /admin/categories(.:format)          {:action=>"index", :controller=>"admin/categories"}
#                            POST       /admin/categories(.:format)          {:action=>"create", :controller=>"admin/categories"}
#         new_admin_category GET        /admin/categories/new(.:format)      {:action=>"new", :controller=>"admin/categories"}
#        edit_admin_category GET        /admin/categories/:id/edit(.:format) {:action=>"edit", :controller=>"admin/categories"}
#             admin_category GET        /admin/categories/:id(.:format)      {:action=>"show", :controller=>"admin/categories"}
#                            PUT        /admin/categories/:id(.:format)      {:action=>"update", :controller=>"admin/categories"}
#                            DELETE     /admin/categories/:id(.:format)      {:action=>"destroy", :controller=>"admin/categories"}
#           admin_news_index GET        /admin/news(.:format)                {:action=>"index", :controller=>"admin/news"}
#                            POST       /admin/news(.:format)                {:action=>"create", :controller=>"admin/news"}
#             new_admin_news GET        /admin/news/new(.:format)            {:action=>"new", :controller=>"admin/news"}
#            edit_admin_news GET        /admin/news/:id/edit(.:format)       {:action=>"edit", :controller=>"admin/news"}
#                 admin_news GET        /admin/news/:id(.:format)            {:action=>"show", :controller=>"admin/news"}
#                            PUT        /admin/news/:id(.:format)            {:action=>"update", :controller=>"admin/news"}
#                            DELETE     /admin/news/:id(.:format)            {:action=>"destroy", :controller=>"admin/news"}
#     new_admin_user_session GET        /admin/login(.:format)               {:action=>"new", :controller=>"active_admin/devise/sessions"}

app/models/car.rb
class Car < ActiveRecord::Base
  acts_as_votable
  has_many :pictures, :as => :imageable
  accepts_nested_attributes_for :pictures

  has_many :comments, :as => :commentable
	attr_accessible :name, :model_id, :description, :car_type, 
                  :year, :price, :transmission, :drive_type,
                  :horsepower, :engine, :fuel_type, :seating_capacity, :pictures_attributes
  
  belongs_to :model
  has_many :reviews, :as => :reviewable
  has_many :options, :dependent => :destroy
  has_many :comforts
  has_many :entertainments
  has_many :safeties
  
  scope :body_style, proc { |body_style| where(:body_style => body_style) }
  scope :discount, proc { |discount| where(:discount => discount) }
  scope :new_cars, where(:car_type => "new")
  scope :used_cars, where(:car_type => "used")
  scope :featured, where("discount > 10").order("discount DESC").limit(5)


end

app/controllers/cars_controller.rb
class CarsController < InheritedResources::Base
  layout 'auto/cars'
  has_scope :body_style
  has_scope :discount

  before_filter :categories

  def index
  	@search = Car.search(params[:search])
    @cars = @search.page(params[:page]).per(15)
    @pictures = Picture.cars
    @news = News.cars
    render "params" if !@car.nil?
  end

  def show
    @car = Car.find(params[:id])
    @options = @car.options
    @car.liked_by User.first
    @review = Review.new
    @similar_cars = Car.where(:engine => @car.engine).limit(10)
  end

  def news
    @news = News.cars
  end

  def new_cars
    @search = apply_scopes(Car.new_cars).search(params[:search])
    @cars = @search.page(params[:page]).per(15)
    render "params"
  end
  
  def used_cars
    @search = apply_scopes(Car.used_cars).search(params[:search])
    @cars = @search.page(params[:page]).per(15)
    render "params"
  end

  def categories
    @makes = Make.all
    @models = Model.all
  end

  def news
    @news = News.cars
  end

end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_car.html.erb
<div class="wrapper">
  <tr>
    <td><%= link_to image_tag("auto/img2.jpg", :size => '100x70', :class => "img-indent"), car %></td>
    <td>
      <h4>
        <%=  %>
        <%= link_to car.year.to_s+" "+car.name, car %>
      </h4>
    </td>
    <td><span class="price fleft">$<%= car.price %></span></td>
    <td><%= car.likes.size %></td>
  </tr>
</div>

app/views/cars/_car_show.html.erb
<table>
	<tr>
		<td>
			<%= image_tag @car.pictures.first.image.url, :width => 150 if @car.pictures.exists? %>
		</td>
		<td>
			<h4><%= @car.name %></h4>
			<h4><%= @car.model.name %></h4>
			<h4><%= number_to_currency @car.price %></h4>

		</td>
	</tr>
	
</table>

app/views/cars/_featured.html.erb
<h3>Featured cars</h3>
 	<% for car in Car.featured %>
 		<%= link_to car.name, car %><br />
 		Discount: <%= number_to_percentage car.discount %>
	 	<% if car.pictures.exists? %>
	    	<%= link_to image_tag(car.pictures.first.image.url, :width => 200), car  %>
	    <% end %>
	    <br />
 	<% end %>

app/views/cars/_left_main.html.erb
<% content_for :left do %>
  <h3>Used Cars</h3>
  <div class="indent">
  <h4>Body Style</h4>
  	<ul class="p3">
      <li><%= link_to "Hatchback", used_cars_path+"?body_style=hatchback" %></li>
      <li><%= link_to "Coupe", used_cars_path+"?body_style=coupe" %></li>
      <li><%= link_to "Sedan", used_cars_path+"?body_style=sedan" %></li>
      <li><%= link_to "Truck", used_cars_path+"?body_style=truck" %></li>
      <li><%= link_to "SUV", used_cars_path+"?body_style=suv" %></li>
      <li><%= link_to "Crossover", used_cars_path+"?body_style=crossover" %></li>
      <li><%= link_to "Convertible", used_cars_path+"?body_style=convertible" %></li>
      <li><%= link_to "Van", used_cars_path+"?body_style=van" %></li>
      <li><%= link_to "Wagon", used_cars_path+"?body_style=wagon" %></li>
    </ul>
    <ul class="last">
      <li><%= link_to "All Used Cars", used_cars_path %></li>
    </ul>
  </div>
<% end %>

app/views/cars/_right_main.html.erb
<% content_for :right do %>

<% end %>

app/views/cars/_right_show.html.erb
<% content_for :right do %>
 <div class="indent">
 <h4>Details</h4>
 	<ul class="p3">
 		<li><%= link_to "Overview", car_path(@car) %></li>
 		<li><%= link_to "Pictures", car_pictures_path(@car) %></li>
 		<li><%= link_to "Options", car_options_path(@car) %></li>
 		<li><%= link_to "User reviews", car_reviews_path(@car) %></li>
 	</ul>
 	</div>
 <% end %>

app/views/cars/index.html.erb
  <%= render :partial => "right_main" %>
  <%= render :partial => "left_main" %>

  <%= form_for @search, :url => cars_path do |f| %>
  <div class="inline">
  <h4>Select make</h4>
    <%= f.collection_checks :model_make_id_in, Make.all,
          :id, :name, :class => 'headcheck', :id => "sfg" do |check| %>
          <%= check.box %>
          <%= check.label %>
        <br />
      <% end %>  
   
  
</div>  
<div class="inline">
  <h4>Price</h4>
        <%= f.label :price_gte, "From" %>
        <%= f.text_field :price_gte, :size => 5 %>
        <%= f.label :price_lte, "to" %>
        <%= f.text_field :price_lte, :size => 5 %>
      <h4>Year</h4>
        <%= f.label :year_gte, "From" %>
        <%= f.text_field :year_gte, :size => 5 %>
        <%= f.label :year_lte, "to" %>
        <%= f.text_field :year_lte, :size => 5 %>
      <h4>Horsepower</h4>
      <div>
        <%= f.label :horsepower_gte, "From" %>
        <%= f.text_field :horsepower_gte, :size => 5 %>
        <%= f.label :horsepower_lte, "to" %>
        <%= f.text_field :horsepower_lte, :size => 5 %>
      </div>
      </div>
      <p><%= f.submit "Search", :name => "Search" %></p>
    <% end %>

<h2>Recommended</h2>

   <div id="cars">
  <%= paginate @cars %>
<table> 
<tr>
    <td><h6>Photo</h6></td>
    <td><h6><%= sort_link @search, :name, "Model" %></h6></td>
    <td><h6><%= sort_link @search, :price %></h6></td>
    <td>Views</td>
  </tr>
  <%= render @cars %>
</table>
  <%= paginate @cars %>
</div>
     
<% content_for :right do %>
  
  <% for car in Car.limit(10) %>
    <% if car.pictures.exists? %>
      <%= link_to car.name, car %>
      <%= link_to image_tag(car.pictures.first.image.url, :width => 200), car %>
    <% end %>
  <% end %>
  
<% end %>

app/views/cars/news.html.erb
<%= render @news %>

<%= render :partial => "right_main" %>  

app/views/cars/params.html.erb
<%= content_for :right do %>
<h3>Information</h3>
<div class="indent_param">

<%= form_for [:auto, @search], :url => url_for(:action => action_name) do |f| %>
<div class="param">
        <p><%= f.label :name_contains %></p>
        <%= f.text_field :name_contains, :size => 24 %>
      </div>
      <h2>Make</h2>
      <div class="param">
    	  <% f.collection_checks(:model_make_id_in, Make.all,
    	      :id, :name, :class => 'headcheck').in_groups_of(2, false) do |check| %>
    	    <% check.each do |check| %>
            <%= check.box %>
            <%= check.label %>
          <% end %>
          <br />
    	  <% end %>
      </div>
      <h2>Price</h2>
      <div>
        <%= f.label :price_gte, "From" %>
        <%= f.text_field :price_gte, :size => 5 %>
        <%= f.label :price_lte, "to" %>
        <%= f.text_field :price_lte, :size => 5 %>
      </div>
      <h2>Year</h2>
      <div>
        <%= f.label :year_gte, "From" %>
        <%= f.text_field :year_gte, :size => 5 %>
        <%= f.label :year_lte, "to" %>
        <%= f.text_field :year_lte, :size => 5 %>
      </div>
      <h2>Body Style</h2>
      <div class="param">
        <% f.checks(:body_style_in,
           [['Hatchback', 'hatchback'], ['Coupe', 'coupe'], ['Sedan', 'sedan'],
           ['Truck', 'truck'], ['SUV', 'suv'], ['Crossover', 'crossover'],
           ['Convertible', 'convertible'], ['Van', 'van'], ['Wagon', 'wagon']],
           :class => 'checkboxy').in_groups_of(2, false) do |checks| %>
          <% checks.each do |check| %>
            <%= check.box %>
            <%= check.label %>
          <% end %>
          <br />
        <% end %>
      </div>
      <h2>Transmission</h2>
      <div class="param">
        <% f.checks(:transmission_in,
           [['Automatic', 'automatic'],['Manual', 'manual']],
           :class => 'checkboxy').in_groups_of(2, false) do |checks| %>
          <% checks.each do |check| %>
            <%= check.box %>
            <%= check.label %>
          <% end %>
        <% end %>
      </div>
      <h2>Drive Type</h2>
      <div class="param">
        <% f.checks(:drive_type_in,
           [['2WD', 'two_wd'],['4WD', 'four_wd'],['AWD', 'all_wd']],
           :class => 'checkboxy').in_groups_of(2, false) do |checks| %>
          <% checks.each do |check| %>
            <%= check.box %>
            <%= check.label %>
          <% end %>
        <% end %>
      </div>
      <h2>Horsepower</h2>
      <div>
        <%= f.label :horsepower_gte, "From" %>
        <%= f.text_field :horsepower_gte, :size => 5 %>
        <%= f.label :horsepower_lte, "to" %>
        <%= f.text_field :horsepower_lte, :size => 5 %>
      </div>
      <h2>Engine</h2>
      <div>
        <%= f.label :engine_gte, "From" %>
        <%= f.text_field :engine_gte, :size => 5 %>
        <%= f.label :engine_lte, "to" %>
        <%= f.text_field :engine_lte, :size => 5 %>
      </div>
      <h2>Fuel Type</h2>
      <div class="param">
        <% f.checks(:fuel_type_in,
           [['Diesel', 'diesel'],['Electric', 'electric'],['Ethanol', 'ethanol'],
           ['Gasoline', 'gasoline'],['Hybrid', 'hybrid'],['Natural Gas', 'natural_gas']],
           :class => 'checkboxy').in_groups_of(2, false) do |checks| %>
          <% checks.each do |check| %>
            <%= check.box %>
            <%= check.label %>
          <% end %>
          <br />
        <% end %>
      </div>
      <h2>Seating Capacity</h2>
      <div>
        <%= f.label :seating_capacity_gte, "From" %>
        <%= f.text_field :seating_capacity_gte, :size => 5 %>
        <%= f.label :seating_capacity_lte, "to" %>
        <%= f.text_field :seating_capacity_lte, :size => 5 %>
      </div>
      <h2>Towing Capacity</h2>
      <div>
        <%= f.label :towing_capacity_gte, "From" %>
        <%= f.text_field :towing_capacity_gte, :size => 5 %>
        <%= f.label :towing_capacity_lte, "to" %>
        <%= f.text_field :towing_capacity_lte, :size => 5 %>
      </div>
      <h2>Safety</h2>
      <div>
        <%= f.label :towing_capacity_gte, "From" %>
        <%= f.text_field :towing_capacity_gte, :size => 5 %>
        <%= f.label :towing_capacity_lte, "to" %>
        <%= f.text_field :towing_capacity_lte, :size => 5 %>
      </div>
      <h2>Discount</h2>
      <div>
        <%= f.label :discount_gte, "From" %>
        <%= f.text_field :discount_gte, :size => 5 %>
        <%= f.label :discount_lte, "to" %>
        <%= f.text_field :discount_lte, :size => 5 %>
      </div>


    <p><%= f.submit "Search", :class => "submit" %></p>

<% end %>

</div>
<% end %>

<div id="cars">
  <%= paginate @cars %>
<table> 
<tr>
    <td><h6>Photo</h6></td>
    <td><h6><%= sort_link @search, :name, "Model" %></h6></td>
    <td><h6><%= sort_link @search, :price %></h6></td>
    <td>Views</td>
  </tr>
  <%= render @cars %>
</table>
  <%= paginate @cars %>
</div>

<% content_for :left do %>
  <%= render :partial => "left_main" %>
<% end %>

app/views/cars/show.html.erb
<%= render :partial => "car_show" %>


<ul id="demo-ul">
	<li class="open">
		<p>Anti-Theft & Locks</p>
		<ul>
			<% for option in @options.car_params("Anti-Theft & Locks") %>
				<li><a><%= option.name %></a></li>
			<% end %>
			
		</ul>
	</li>
	<li>
		<p>Braking & Traction</p>
		<ul>
			<% for option in @options.car_params("Braking & Traction") %>
				<li><a><%= option.name %></a></li>
			<% end %>
			
		</ul>
	</li>
	<li>
		<p>Engines & Emissions</p>
		<ul>
			<% for option in @options.car_params("Engines & Emissions") %>
				<li><a><%= option.name %></a></li>
			<% end %>
			
		</ul>
	</li>
	
</ul>
 
 <%= render :partial => 'right_show' %>

 <%= content_for :left do %>
 	<h3>Similar cars</h3>
 	<% for car in @similar_cars %>
	 	<% if car.pictures.exists? %>
	 		<%= link_to car.name, car %>
	    	<%= link_to image_tag(car.pictures.first.image.url, :width => 200), car  %>
	    <% end %>
 	<% end %>
	
 <% end %>