config/routes.rb
Kurs::Application.routes.draw do
  
  

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users

  resources :users do
    resources :carts
  end

  match 'cars/news' => 'cars#news'

  resources :makes
  resources :models
  resources :cars do
    resources :pictures
    resources :options
    resources :reviews
    resources :news
  end

  resources :line_items, :only => [:create, :destroy]
  
  match 'movies/latest' => 'movies#latest'
  match 'movies/top_rated' => 'movies#top_rated'
  match 'movies/coming' => 'movies#coming'
  match 'movies/top_commented' => 'movies#top_commented'
  match 'movies/votes' => 'movies#votes'
  match 'movies/comments' => 'movies#index'
  match 'movies/search' => "movies#search"

  resources :movies, :only => [:index, :show] do
    resources :comments
  end

  match 'auto' => 'auto/cars#index'
  match 'auto/news' => 'auto/cars#news'
  match 'new_cars' => 'cars#new_cars'
  match 'used_cars' => 'cars#used_cars'

  resources :news, :only => [:index, :show] do
    resources :comments
  end

  resources :categories, :only => [:index, :show] do
    resources :products, :only => [:index, :show]
  end

  resources :manufacturers, :only => [:show]

  resources :products, :only => [:index]
  

  root :to => 'pages#home'

  match 'our_news' => 'pages#news'
  match 'our_services' => 'pages#services'
  match 'our_products' => 'pages#products'
  match 'contacts' => 'pages#contacts'
  
end
#== Route Map
# Generated on 25 Sep 2011 20:32
#
#                 auto_makes GET        /auto/makes(.:format)                {:action=>"index", :controller=>"auto/makes"}
#                            POST       /auto/makes(.:format)                {:action=>"create", :controller=>"auto/makes"}
#              new_auto_make GET        /auto/makes/new(.:format)            {:action=>"new", :controller=>"auto/makes"}
#             edit_auto_make GET        /auto/makes/:id/edit(.:format)       {:action=>"edit", :controller=>"auto/makes"}
#                  auto_make GET        /auto/makes/:id(.:format)            {:action=>"show", :controller=>"auto/makes"}
#                            PUT        /auto/makes/:id(.:format)            {:action=>"update", :controller=>"auto/makes"}
#                            DELETE     /auto/makes/:id(.:format)            {:action=>"destroy", :controller=>"auto/makes"}
#                auto_models GET        /auto/models(.:format)               {:action=>"index", :controller=>"auto/models"}
#                            POST       /auto/models(.:format)               {:action=>"create", :controller=>"auto/models"}
#             new_auto_model GET        /auto/models/new(.:format)           {:action=>"new", :controller=>"auto/models"}
#            edit_auto_model GET        /auto/models/:id/edit(.:format)      {:action=>"edit", :controller=>"auto/models"}
#                 auto_model GET        /auto/models/:id(.:format)           {:action=>"show", :controller=>"auto/models"}
#                            PUT        /auto/models/:id(.:format)           {:action=>"update", :controller=>"auto/models"}
#                            DELETE     /auto/models/:id(.:format)           {:action=>"destroy", :controller=>"auto/models"}
#                  auto_cars GET        /auto/cars(.:format)                 {:action=>"index", :controller=>"auto/cars"}
#                            POST       /auto/cars(.:format)                 {:action=>"create", :controller=>"auto/cars"}
#               new_auto_car GET        /auto/cars/new(.:format)             {:action=>"new", :controller=>"auto/cars"}
#              edit_auto_car GET        /auto/cars/:id/edit(.:format)        {:action=>"edit", :controller=>"auto/cars"}
#                   auto_car GET        /auto/cars/:id(.:format)             {:action=>"show", :controller=>"auto/cars"}
#                            PUT        /auto/cars/:id(.:format)             {:action=>"update", :controller=>"auto/cars"}
#                            DELETE     /auto/cars/:id(.:format)             {:action=>"destroy", :controller=>"auto/cars"}
#               auto_options GET        /auto/options(.:format)              {:action=>"index", :controller=>"auto/options"}
#                            POST       /auto/options(.:format)              {:action=>"create", :controller=>"auto/options"}
#            new_auto_option GET        /auto/options/new(.:format)          {:action=>"new", :controller=>"auto/options"}
#           edit_auto_option GET        /auto/options/:id/edit(.:format)     {:action=>"edit", :controller=>"auto/options"}
#                auto_option GET        /auto/options/:id(.:format)          {:action=>"show", :controller=>"auto/options"}
#                            PUT        /auto/options/:id(.:format)          {:action=>"update", :controller=>"auto/options"}
#                            DELETE     /auto/options/:id(.:format)          {:action=>"destroy", :controller=>"auto/options"}
#            auto_categories GET        /auto/categories(.:format)           {:action=>"index", :controller=>"auto/categories"}
#                            POST       /auto/categories(.:format)           {:action=>"create", :controller=>"auto/categories"}
#          new_auto_category GET        /auto/categories/new(.:format)       {:action=>"new", :controller=>"auto/categories"}
#         edit_auto_category GET        /auto/categories/:id/edit(.:format)  {:action=>"edit", :controller=>"auto/categories"}
#              auto_category GET        /auto/categories/:id(.:format)       {:action=>"show", :controller=>"auto/categories"}
#                            PUT        /auto/categories/:id(.:format)       {:action=>"update", :controller=>"auto/categories"}
#                            DELETE     /auto/categories/:id(.:format)       {:action=>"destroy", :controller=>"auto/categories"}
#                       auto            /auto(.:format)                      {:action=>"auto", :controller=>"pages"}
#             auto_cars_news            /auto/cars/news(.:format)            {:controller=>"auto/cars", :action=>"news"}
#            admin_dashboard            /admin(.:format)                     {:action=>"index", :controller=>"admin/dashboard"}
#             admin_comments GET        /admin/comments(.:format)            {:action=>"index", :controller=>"admin/comments"}
#                            POST       /admin/comments(.:format)            {:action=>"create", :controller=>"admin/comments"}
#          new_admin_comment GET        /admin/comments/new(.:format)        {:action=>"new", :controller=>"admin/comments"}
#         edit_admin_comment GET        /admin/comments/:id/edit(.:format)   {:action=>"edit", :controller=>"admin/comments"}
#              admin_comment GET        /admin/comments/:id(.:format)        {:action=>"show", :controller=>"admin/comments"}
#                            PUT        /admin/comments/:id(.:format)        {:action=>"update", :controller=>"admin/comments"}
#                            DELETE     /admin/comments/:id(.:format)        {:action=>"destroy", :controller=>"admin/comments"}
#             admin_products GET        /admin/products(.:format)            {:action=>"index", :controller=>"admin/products"}
#                            POST       /admin/products(.:format)            {:action=>"create", :controller=>"admin/products"}
#          new_admin_product GET        /admin/products/new(.:format)        {:action=>"new", :controller=>"admin/products"}
#         edit_admin_product GET        /admin/products/:id/edit(.:format)   {:action=>"edit", :controller=>"admin/products"}
#              admin_product GET        /admin/products/:id(.:format)        {:action=>"show", :controller=>"admin/products"}
#                            PUT        /admin/products/:id(.:format)        {:action=>"update", :controller=>"admin/products"}
#                            DELETE     /admin/products/:id(.:format)        {:action=>"destroy", :controller=>"admin/products"}
#           admin_categories GET        /admin/categories(.:format)          {:action=>"index", :controller=>"admin/categories"}
#                            POST       /admin/categories(.:format)          {:action=>"create", :controller=>"admin/categories"}
#         new_admin_category GET        /admin/categories/new(.:format)      {:action=>"new", :controller=>"admin/categories"}
#        edit_admin_category GET        /admin/categories/:id/edit(.:format) {:action=>"edit", :controller=>"admin/categories"}
#             admin_category GET        /admin/categories/:id(.:format)      {:action=>"show", :controller=>"admin/categories"}
#                            PUT        /admin/categories/:id(.:format)      {:action=>"update", :controller=>"admin/categories"}
#                            DELETE     /admin/categories/:id(.:format)      {:action=>"destroy", :controller=>"admin/categories"}
#           admin_news_index GET        /admin/news(.:format)                {:action=>"index", :controller=>"admin/news"}
#                            POST       /admin/news(.:format)                {:action=>"create", :controller=>"admin/news"}
#             new_admin_news GET        /admin/news/new(.:format)            {:action=>"new", :controller=>"admin/news"}
#            edit_admin_news GET        /admin/news/:id/edit(.:format)       {:action=>"edit", :controller=>"admin/news"}
#                 admin_news GET        /admin/news/:id(.:format)            {:action=>"show", :controller=>"admin/news"}
#                            PUT        /admin/news/:id(.:format)            {:action=>"update", :controller=>"admin/news"}
#                            DELETE     /admin/news/:id(.:format)            {:action=>"destroy", :controller=>"admin/news"}
#     new_admin_user_session GET        /admin/login(.:format)               {:action=>"new", :controller=>"active_admin/devise/sessions"}

app/models/product.rb
class Product < ActiveRecord::Base

	has_many :pictures, :as => :imageable
  accepts_nested_attributes_for :pictures

  attr_accessible :pictures_attributes

	belongs_to :category
	belongs_to :manufacturer
	has_many :line_items
	has_many :reviews, :as => :reviewable

	scope :latest, order("created_at DESC").limit(9)

	def self.search(search, category)
		if category	
			if search
				category.products.where('name LIKE ?', "%#{search}%")
			else
				scoped
			end
		else
			if search
				where('name LIKE ?', "%#{search}%")
			else
				scoped
			end
		end
	end

end

app/controllers/products_controller.rb
class ProductsController < InheritedResources::Base
	before_filter :authenticate_user!
	before_filter :load_cart
	layout "store/store"
	belongs_to :category

	def load_cart
		@categories = Category.all
		@manufacturers = Manufacturer.all
		@cart = current_user.carts.last
	end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product.html.erb
<div class="prod_box">
	<div class="top_prod_box"></div>
    <div class="center_prod_box">            
         <div class="product_title"><%= link_to product.name, category_product_path(product.category, product) %></div>
         <div class="product_img">
         		<% if product.pictures.exists? %>
        			<%= link_to image_tag(product.pictures.first.image.url), [product.category, product] %>   
        		<% else %>
        			<%= link_to image_tag("store/laptop.png"), [product.category, product] %> 
        		<% end %>
         </div>
         <div class="prod_price"><span class="reduce"></span> <span class="price"><%= number_to_currency(product.price) %></span></div>                        
    </div>
    <div class="bottom_prod_box"></div>             
    <div class="prod_details_tab">
    <%= button_to "To Cart", line_items_path(:product_id => product.id), 
                                                :remote => true,
                                                :class => "addtocart",
                                                :disable_with => 'Wait...' %>
    <%= link_to "details", category_product_path(product.category, product), :class => "prod_details" %>
    </div>
</div>

app/views/products/index.html.erb
<div class="center_title_bar">Latest Products</div>
    
    	<div class="prod_box">
      	<div class="top_prod_box"></div>
          <div class="center_prod_box">            
               <div class="product_title"><a href="details.html">Motorola 156 MX-VL</a></div>
               <div class="product_img"><a href="details.html"><img src="images/store/laptop.gif" alt="" title="" border="0" /></a></div>
               <div class="prod_price"><span class="reduce">350$</span> <span class="price">270$</span></div>                        
          </div>
          <div class="bottom_prod_box"></div>             
          <div class="prod_details_tab">
          <a href="#" title="header=[Add to cart] body=[&nbsp;] fade=[on]"><img src="images/store/cart.gif" alt="" title="" border="0" class="left_bt" /></a>
          <a href="#" title="header=[Specials] body=[&nbsp;] fade=[on]"><img src="images/store/favs.gif" alt="" title="" border="0" class="left_bt" /></a>
          <a href="#" title="header=[Gifts] body=[&nbsp;] fade=[on]"><img src="images/store/favorites.gif" alt="" title="" border="0" class="left_bt" /></a>           
          <a href="details.html" class="prod_details">details</a>            
          </div>                     
      </div>

      
 
 <div class="center_title_bar">Recommended Products</div>
 
 
      	<div class="prod_box">
        	<div class="top_prod_box"></div>
            <div class="center_prod_box">            
                 <div class="product_title"><a href="details.html">Motorola 156 MX-VL</a></div>
                 <div class="product_img"><a href="details.html"><img src="images/store/laptop.gif" alt="" title="" border="0" /></a></div>
                 <div class="prod_price"><span class="reduce">350$</span> <span class="price">270$</span></div>                        
            </div>
            <div class="bottom_prod_box"></div>             
            <div class="prod_details_tab">
            <a href="#" title="header=[Add to cart] body=[&nbsp;] fade=[on]"><img src="images/store/cart.gif" alt="" title="" border="0" class="left_bt" /></a>
            <a href="#" title="header=[Specials] body=[&nbsp;] fade=[on]"><img src="images/store/favs.gif" alt="" title="" border="0" class="left_bt" /></a>
            <a href="#" title="header=[Gifts] body=[&nbsp;] fade=[on]"><img src="images/store/favorites.gif" alt="" title="" border="0" class="left_bt" /></a>           
            <a href="details.html" class="prod_details">details</a>            
            </div>                     
        </div>

app/views/products/show.html.erb
<div class="center_title_bar"><%= @product.name %></div>
    
    	<div class="prod_box_big">
        	<div class="top_prod_box_big"></div>
            <div class="center_prod_box_big">            
                 <%= render @product.pictures %>
                 
                     <div class="details_big_box">
                         <div class="product_title_big"><%= @product.name %></div>
                         <div class="specifications">
                            Assignment: <span class="blue"><%= @product.assignment %></span><br />

                            Design: <span class="blue"><%= @product.design %></span><br />
                            
                            Construction: <span class="blue"><%= @product.construction %></span><br />
                            
                            Description: <span class="blue"><%= @product.description %>$</span><br />
                         </div>
                         <div class="prod_price_big"><span class="reduce">350$</span>
                            <span class="price"><%= @product.price %>$</span></div>
                         <%= button_to "To Cart", line_items_path(:product_id => @product), 
                                                      :remote => true,
                                                      :disable_with => "Wait...",
                                                      :class => "addtocart" %>
                         
                     </div>   
                                          
            </div>
            <div class="bottom_prod_box_big"></div>                                
        </div>

    <%= render @product.reviews %>